version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  randomapp:
    image: docker.pkg.github.com/clabroche/docker-registry/randomapp:latest
    hostname: randomapp
    restart: always
    environment:
      PORT: 9878
      mongoDbURL: mongodb://root:apasswordtochange@mongodb/randomapp?authSource=admin
    labels:
      com.centurylinklabs.watchtower.enable: "true"

    expose:
      - 9878
    ports:
      - 9878:9878
    links:
      - mongodb
  mongodb:
    image: mongo:4
    hostname: mongodb
    restart: always
    expose:
      - 2039
    ports:
      - 2039:2039
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: apasswordtochange
    command: mongod --port 2039
    volumes:
      - ./mongo-volume:/data/db
