name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8

    - name: Checkout
      uses: actions/checkout@master

    - name: Install dependencies
      run: npm ci

    - name: Build dependencies
      run: npm run build

    - name: Build apk
      run: npm run capacitor:build

    - name: Android apksigner
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEY_STORE_FILE }}
        alias: ${{ secrets.KEY_STORE_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Move signed apk
      run: mv ${SIGNED_RELEASE_FILE} dist/randomapp.apk

    - name: Remove useless artifact
      run: rm -r dist/bundled

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        name: clabroche/docker-registry/randomapp
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.pkg.github.com
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
  